Repository thekavikumar/Gallery, pull requests merged in 2022-10, with the labels that each got.

#5 Issue solved #4
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#10 Update on the issue #7
  src/index.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#11 Update on issue #6
  src/components/Title.js
Labels: hacktoberfest, hacktoberfest-accepted

#13 Update on issue #12
  public/favicon.png
  public/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#15 Update on issue #14
  src/components/Title.js
Labels: hacktoberfest, hacktoberfest-accepted

#20 adding dynamic changing of quotes in login and home page
  src/components/Home.js
  src/components/Title.js
Labels: hacktoberfest-accepted

#21 Updating shadow color dynamically
  src/components/Home.js
  src/components/Login.js
  src/components/Title.js
Labels: hacktoberfest-accepted

#22 updating the color same as the primary color
  src/components/Login.css
Labels: hacktoberfest-accepted

#26 Update Upload.css
  src/components/Upload.css
Labels: hacktoberfest-accepted

#30 Updatecards
  src/components/Image.css
  src/components/Image.js
Labels: hacktoberfest-accepted

#34 feat: responsive for all screen sizes
  src/components/Ffooter.css
  src/components/Footer.css
  src/components/Image.css
  src/components/Login.css
  src/components/Title.css
Labels: hacktoberfest-accepted

#41 Theme provider handles dark mode state instead of it being separate, and persists the selected theme across reloads
  src/ThemeContextWrapper.js.js
  src/components/Home.js
  src/components/Login.js
  src/components/Title.js
  src/hooks/theme.js
  src/hooks/useTheme.js
  src/index.js
  src/providers/ThemeProvider.js
Labels: hacktoberfest-accepted

#43 Move user state to UserProvider instead of storing it in the Home component
  src/App.js
  src/components/Home.js
  src/components/Image.js
  src/components/Login.js
  src/components/ProgressBar.js
  src/components/Title.js
  src/components/Upload.js
  src/hooks/useUser.js
  src/index.js
  src/providers/UserProvider.js
Labels: hacktoberfest-accepted

#52 Made a better README
  README.md
  src/components/Modal.js
Labels: hacktoberfest-accepted

#60 Consolidate Footer and FFooter into 1 component since they are almost exactly the same
  src/components/Ffooter.css
  src/components/Ffooter.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Home.js
  src/index.css
Labels: hacktoberfest-accepted
